BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"username"	TEXT NOT NULL,
	"secret"	BLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS "config" (
	"key"	TEXT NOT NULL UNIQUE,
	"value"	BLOB,
	PRIMARY KEY("key")
);
CREATE TABLE IF NOT EXISTS "session" (
	"user"	INTEGER NOT NULL,
	"shared_session"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("user")
);
CREATE TABLE IF NOT EXISTS "documents" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"document"	TEXT NOT NULL DEFAULT '{}',
	"title"	TEXT NOT NULL DEFAULT '-',
	"folder"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "folder" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"owner"	INTEGER NOT NULL
);
COMMIT;
